name = "Foxtail"
uuid = "cac871c8-24cd-45c7-943a-574f1c9f15e5"
authors = ["Taka YMMT <dev@ymmt.cc>"]
version = "0.1.0-DEV"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
TSFrames = "9f90e835-9451-4aaa-bcb1-743a1b8d2f84"

[compat]
CSV = "0.10.15"
LinearAlgebra = "1.11.0"
TSFrames = "0.2.2"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
