name = "Foxtail"
uuid = "cac871c8-24cd-45c7-943a-574f1c9f15e5"
authors = ["Taka YMMT <dev@ymmt.cc>"]
version = "0.1-DEV"

[deps]
TSFrames = "9f90e835-9451-4aaa-bcb1-743a1b8d2f84"

[compat]
TSFrames = "0.2.2"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
